### ISSUE TITLE
What changes are in version 1.20.05 ?

### ISSUE THREAD

**Issue by Jimrnelson** [fdbozzo/foxbin2prg#100]
In Thor Check For Updates, I see that the current version is 1.20.05.

Is there a description somewhere of what changes have been made since version 1.19.78?

**Comment by DougHennig** [comment]
For some reason, Change_Log.md is missing. When I merge in recent changes from @lscheffler, I'll make sure that file is included in the repository.

**Comment by lscheffler** [comment]
To bring the project better in line withe the standard, Change_Log.md is changed to ChangeLog.md in my fork, see 
https://github.com/lscheffler/foxbin2prg/blob/fork_mod/docs/ChangeLog.md .   
This is set in the readme of https://github.com/lscheffler/foxbin2prg as well.
