### ISSUE TITLE
DB2 contains values for blank ALIAS2 column

### ISSUE THREAD

**Issue by DougHennig** [fdbozzo/foxbin2prg#104]
## ℹ Computer information

- VFP version: VFPA 10.00.0000.2304 (but not relevant because this issue runs FoxBin2PRG.exe)
- FoxBin2PRG version: 1.20
- Last FoxBin2PRG version w/o bug (if available): unknown

## 📝 Provide detailed reproduction steps (if any)

1. Ensure FoxBin2Prg.cfg contains DBF_Conversion_Support: 8 so it creates a DB2 file.
2. Run FoxBin2.exe on the attached Repmeta.dbf

### ✔️ Expected result

The ALIAS2 value in the DB2 file is empty since that column in empty in the DBF.

### ❌ Actual result

The DB2 contains <ALIAS2>ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg</ALIAS2>
[REPMETA.zip](https://github.com/fdbozzo/foxbin2prg/files/13690238/REPMETA.zip)

This is the only column I have seen this happen in so I suspect the issue is the column name clashing with a variable name in FoxBin2PRG.

**Comment by lscheffler** [comment]
@DougHennig 
### Step 1
Recreation of the file runs fine.
### Step 2
The value of the field Alias2 in the DB2 file is correctly translated.
Alias2 is *Character(binary)*. IOW *NoCPTrans*

So the field value will be stored as `Strconv(Value,13)`; where ICAg is just a space.

**Comment by DougHennig** [comment]
Thanks for the explanation.

**Comment by GerhardSchmidbauer** [comment]
My husband Gerhard has died December 6. ; please cancel all Maild and
Abos. Thank you! 

Claudia Schmidbauer, Germany 

Am 16.12.2023 14:05, schrieb Doug Hennig: 

> Thanks for the explanation. 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

 

Links:
------
[1]
https://github.com/fdbozzo/foxbin2prg/issues/104#issuecomment-1858814216
[2]

**Comment by GerhardSchmidbauer** [comment]
My husband Gerhard died December 6. - Please stop all mails and abos.
Thank you. 

Claudia Schmidbauer, Germany. 

--- 

Am 16.12.2023 13:22, schrieb Lutz Scheffler: 

> Closed #104 [1] as completed. 
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

 

Links:
------
[1] https://github.com/fdbozzo/foxbin2prg/issues/104
[2] https://github.com/fdbozzo/foxbin2prg/issues/104#event-11265669666
[3]

**Comment by DougHennig** [comment]
I am very sorry to hear that, Claudia. I always appreciated his contributions to our community. Unfortunately, I cannot stop GitHub from sending emails. You can cancel his GitHub account.

**Comment by lscheffler** [comment]
@GerhardSchmidbauer 
Sehr geehrte Frau Schmidbauer,

Ich möchte Ihnen mein tief empfundenes Beileid ausdrücken. Gerhard war ein langjähriger Freund und ein wertvoller Teil unserer Gemeinschaft. Wir werden ihn vermissen.

Es ist für uns leider nicht möglich, Benachrichtigungen zu unterdrücken, diese gehen immer vom Nutzer aus.    
Es wäre am einfachsten, wenn Sie die Mitgliedschaft in github beenden würden.
Falls Sie die Zugangsdaten zu github haben, folgen Sie dazu https://github.com/settings/admin, ganz unten gibt es *Delete Account* oder so etwas. Sonst wird das leider umständlich.

Allerdings denke ich, dass eventuell einige weitere Mitglieder unserer Gemeinschaft ihr Beileid ausdrücken möchten, und Sie mit dem Löschen noch ein paar Tage warten sollten.

Ich werde die Gemeinschaft in www.levelextreme.com, in der Gerhard lange Jahre aktiv war, informieren.

Lutz Scheffler
