### ISSUE TITLE
Tabs stripped out of memos when DB2 is converted to DBF

### ISSUE THREAD

**Issue by DougHennig** [fdbozzo/foxbin2prg#13]
When FoxBin2PRG converts a DB2 file to a DBF file and imports the data (using DBF_Conversion_Support = 8), tabs at the start of lines in memo fields are lost because the Set_Line method of CL_CUS_BASE uses this code:

	tcLine 	= LTRIM( taCodeLines(I), 0, CHR(9), ' ' )

For example:

		This is some text

becomes:

	This is some text

when FoxBin2PRG restores the data.

I think the Set_line method of CL_CUS_RECORD should override this method and use:

	tcLine 	= taCodeLines(I)

instead. That way, data is correctly restored.

**Comment by fdbozzo** [comment]
Hi Doug! It's fixed on v1.19.49.5

Please, check if it's work for you too,

Thanks!

**Comment by DougHennig** [comment]
Yes, that works. Thanks and Merry Christmas!
