### ISSUE TITLE
FoxBin2PRG not ignoring obsolete records

### ISSUE THREAD

**Issue by DougHennig** [fdbozzo/foxbin2prg#15]
It appears that the Class Designer does not always remove records from the VCX for controls that were deleted in a class. For example, in the attached Test.zip, open the PanelTextFormat class in FRXPanels.vcx and you will see this:

![paneltextformatoriginal](https://user-images.githubusercontent.com/12052409/34581407-e6aed988-f155-11e7-9a78-a3275d1da557.png)

However, if you USE FRXPANELS.VCX and BROWSE FOR OBJNAME = 'paneltextformat' OR PARENT = 'paneltextformat', you will find some records that belong to the class that you do not see in the Class Designer: records for objects named Shp1, previewText, LBL1, Lbl4, Lbl2, ad Lbl3. These all have RECNO() values less than the record for the class itself (record 400). Somehow, the Class Designer knows to ignore the extra records (I am guessing it ignores records with RECNO() less than the class record's RECNO).

The problem comes up when you use FoxBin2PRG to convert the VCX to a VC2 file and then from the VC2 to a VCX: when you edit the class, it looks like this in the Class Designer:

![paneltextformatafterconversion](https://user-images.githubusercontent.com/12052409/34581411-e9178a80-f155-11e7-93a8-b8e164b2c847.png)

The objects with arrows are the extra records from the VCX.

So, FoxBin2PRG needs to ignore obsolete records. I looked for a link between the class record and the object records but it appears to be just on PARENT containing the class name. So, FoxBin2PRG will likely have to do what I think the Class Designer does: ignore records with RECNO() less than the class RECNO().

[Test.zip](https://github.com/fdbozzo/foxbin2prg/files/1604506/Test.zip)

**Comment by fdbozzo** [comment]
Hi Doug! It's fixed in v1.19.49.6

Please, confirm it's working for you too.

Best Regards.-

**Comment by DougHennig** [comment]
Yes, it's fixed.
