### ISSUE TITLE
Error, The Specified Key already exists

### ISSUE THREAD

**Issue by Kirides** [fdbozzo/foxbin2prg#17]
I'm receiving the following error while trying to diff a classlib.

The class is properly stringified if i use scctext.
```
2018-01-30T12:24:00  ----------------------------------------------------------------------------
Error 2062, The specified Key already exists.
ignoreincorrectdefinedobjects, 13951
DO c:\portableapps\foxbin2prg\foxbin2prg.exe WITH "C:\...\adresse.vcx"


Error location ..............................
Class: frm_adr_allgemein.Mm_kreditlimitueberwachung
> (no evaluated code yet)
Recno: 368
.............................................
FoxBin2Prg: [C:\PORTABLEAPPS\FOXBIN2PRG\FOXBIN2PRG.EXE] (EXE Version: v1.19.49)
tc_InputFile = [C:\...\ADRESSE.VCX]

Source file: C:\...\adresse.vcx
```

Config:
```
ShowProgressbar: 0
UseClassPerFile: 1
ClassPerFileCheck: 1
ClearUniqueID: 0
```

**Comment by fdbozzo** [comment]
Hi Kirides:

Could you attach or send me in private email the vcx/vct file (zipped) that show this error. I can't reproduce the problem with all the classes y have  :-(

Thanks!

**Comment by DougHennig** [comment]
Hi Fernando.

I've had this happen too but didn't report it. The problem is similar to issue #15 but for the class record itself. For example, I had a VCX that had two records with the same OBJNAME value. One had a lower RECNO() and had nothing in PROPERTIES (although I've also seen records that did have valid values in PROPERTIES), so it was likely replaced by the newer record (the one with the higher RECNO()). I manually deleted the record from the VCX and the error went away.

Doug

**Comment by fdbozzo** [comment]
Ok, I will try to replicate the problem with your example.

**Comment by fdbozzo** [comment]
No luck, have duplicated a vcx record but no error is shown.
A vcx example with this problem could really help me finding the cause and the remedy.

**Comment by Kirides** [comment]
This file especially causes the issue (warning, ~35mb of size, after unzipping)
[adresse.zip](https://github.com/fdbozzo/foxbin2prg/files/1688883/adresse.zip)

**Comment by fdbozzo** [comment]
Fantastic Kirides! I now can reproduce the problem! :)

Back to you when fixed.-

**Comment by fdbozzo** [comment]
Hi Kirides:

Problem is fixed! Please, download the v1.19.49.8 (https://github.com/fdbozzo/foxbin2prg/tree/v1.19.49.8) and let me know if you have any problem.

And many thanks for the example code, that did let me found and fix the bug.

**Comment by Kirides** [comment]
Worked like a charm, good job! :D

**Comment by fdbozzo** [comment]
Nice to hear it! :D
