### ISSUE TITLE
When using the CFG configuration "extension: pj2=pjm" treat the pjm as pj2 and not as SourceSafe-compatible pjm (Darko Kezic)

### ISSUE THREAD

**Issue by fdbozzo** [fdbozzo/foxbin2prg#19]
Originally added as Pull request by Darko Kezic, but is a bug.

**Comment by fdbozzo** [comment]
Fixed in v1.19.50.1

**Comment by fdbozzo** [comment]
Ok, didn't test with the "*" parameter, just with the pjm alone

I'll do some more testing on this and back to you,

Thanks.-

**Comment by fdbozzo** [comment]
Hi Darko!

The "*" parameter part is fixed in [v1.19.50.2](https://github.com/fdbozzo/foxbin2prg/tree/v1.19.50.2)
I've found that in some parts of the code I didn't use the c_PJ2 property abstraction, but the "PJ2" fixed text, and that's why did not work with another substitution. Now it does.

Let me know if this bugfix is working for you too.

Thanks!

**Comment by dkeza** [comment]
It is working now :)

Thank You

**Comment by fdbozzo** [comment]
Fixed in v1.19.50.2
