### ISSUE TITLE
Creating binary files with lower case extensions

### ISSUE THREAD

**Issue by dkeza** [fdbozzo/foxbin2prg#20]
Is it possible to to create binary files where extensions PJX, SCX, VCX etc. are forced to be in lower case?
Now I have differences, because regenerated binary files have file extensions in upper case:
![picture_2](https://user-images.githubusercontent.com/12168379/37390366-135597ae-2768-11e8-933a-ae59c9b57400.png)
![picture_1](https://user-images.githubusercontent.com/12168379/37390367-157f6596-2768-11e8-8558-30ddf6cd4579.png)
Maybe is there already some parameter for this?

**Comment by fdbozzo** [comment]
Hi Darko:

If you are using all the files included in the FoxBin2Prg project, then this is already implemented from the beginning and enabled by default, no parameters needed.

In the same directory of FoxBin2Prg you'll find another EXEs:
- fb2p_diff.exe => To make direct scx/vcx comparisons (text conversions are made in background)
- filename_caps.exe => This program handles the automatic UPPER/lowercase conversions of the files. It uses a filename_caps.cfg configuration file (autodocumented inside) preconfigured for converting to lowercase the extension of the files converted.

When you make a conversion to text or to binary, a LOG is generated explaining the conversion process, which name is the same as the file selected for convertion plus ".log".

In example, if I convert to text a file named "FB2P_TEST.VCX", then a LOG file named "FB2P_TEST.VCX.LOG" is created, which include in the logging the information about the caps convertion (or not), like this example:

```
****************************************************************************************************
CONVERSION PROCESS  2018-03-14T09:36:08
****************************************************************************************************
> USING THIS SETTINGS: C:\DESA\FOXBIN2PRG\FOXBIN2PRG.CFG  => C:\DESA\foxbin2prg\pruebas varias\v1.19.49.4\fb2p_test.vcx
	c_OriginalFileName:           C:\DESA\foxbin2prg\pruebas varias\v1.19.49.4\fb2p_test.vcx

	* Names capitalization program [C:\DESA\FOXBIN2PRG\filename_caps.exe] found
	c_foxbin2prg.changefileattribute >> [C:\DESA\foxbin2prg\pruebas varias\v1.19.49.4\fb2p_test.VC2] lnRet = 0, dwFileAttributes_Orig = -1

	Converting file C:\DESA\foxbin2prg\pruebas varias\v1.19.49.4\fb2p_test.VC2...
		- File: C:\DESA\foxbin2prg\pruebas varias\v1.19.49.4\fb2p_test.VC2 (7.34/7.34 KiB)

```

In this case you can check that the log says that "* Names capitalization program [C:\DESA\FOXBIN2PRG\filename_caps.exe] found", so uses it automatically.

I suggest using the EXE version of FoxBin2Prg, it's faster, but make sure you are using all the EXEs included and that have not copied only foxbin2prg.exe (or prg, which can't work alone).

**Comment by dkeza** [comment]
OK, thank you for this explanation.
I have copied 
```
foxbin2prg.exe
filename_caps.exe
filename_caps.cfg
fb2p_diff.exe
foxbin2prg.cfg
```
to some folder, which is added to system PATH variable, and now when I call foxbin2prg.exe I don't see upper / lower case differences.
My foxbin2prg.cfg looks like this:
```
extension: pj2=pjm
extension: vc2=vca
extension: sc2=sca
extension: fr2=fra
extension: lb2=lba
extension: mn2=mna
extension: db2=dba
extension: dc2=dca
```
I also created small [script](https://gist.github.com/dkeza/3c0b99afa54c1955978ac5ac69f3b168) to easily create text / binary files for opened VFP project.

**Comment by fdbozzo** [comment]
Do not forget to copy **fb2p_diff.cfg** too  :D

Best Regards!

**Comment by dkeza** [comment]
But I don't see fb2p_diff.cfg file anywhere in project?

**Comment by fdbozzo** [comment]
Oh, sorry, I see that didn't include it. You can find it now. This is a link to it, so you don't need to search for it:

https://github.com/fdbozzo/foxbin2prg/blob/master/fb2p_diff.cfg

This CFG just include the configuration to 2 Diff tools, one of which is included with FoxBin2Prg (Winmerge Portable)

**Comment by dkeza** [comment]
OK, i copied also fb2p_diff.cfg, thank you :)
