### ISSUE TITLE
Vistas remotas se corrompen al convertir de texto a binario cuando nombre de vista tiene una o más letras mayúsculas

### ISSUE THREAD

**Issue by skysurfer1** [fdbozzo/foxbin2prg#24]
Me ha sucedido que luego de renombrar una vista remota a un nombre que contiene una o más letras mayúsculas y luego convertir el DBC a su respectivo archivo .DC2 con FoxBin2Prg para luego volver a generar el DBC desde el mismo .DC2, las vistas remotas cuyos nombres son todas letras minúsculas se regeneran bien, pero las vistas que tienen una o más letras mayúsculas pierden el orden y las propiedades de los campos y las vistas no se pueden modificar desde el Administrador de Proyectos de VFP9.

Adjunto archivop .ZIP que contiene ejemplos de vistas y además una versión de FoxBin2Prg que corrige esa falla y pueda servir como base para su corrección oficial.

Saludos.
[DBC_Pruebas.zip](https://github.com/fdbozzo/foxbin2prg/files/1976042/DBC_Pruebas.zip)

**Comment by fdbozzo** [comment]
Gracias SkySurfer1! Lo voy a mirar y probar apenas pueda y te comento :-)

**Comment by fdbozzo** [comment]
Hola SkySurfer1!

Quería agradecerte el arreglo y avisarte de que ya está subido al repositorio principal, junto con otros arreglos necesarios para mantener el ordenamiento alfabético de las vistas, que con el arreglo se había desajustado.

Saludos y gracias!
