### ISSUE TITLE
Cannot generate SC2 file from one particular SCX/SCT form.

### ISSUE THREAD

**Issue by mattslay** [fdbozzo/foxbin2prg#29]
FoxBin2Prg has stopped working with this particular Form (SCX/SCT) for some reason. It used to work fine with this file. Zip files attached containing 2 files. I call the 

[Quotes-Matt-Slay-Issue.zip](https://github.com/fdbozzo/foxbin2prg/files/2533743/Quotes-Matt-Slay-Issue.zip)

I call it this way:

Do "H:\Thor\Thor\Tools\Components\FoxBIN2PRG\FoxBin2Prg.prg" with "H:\Work\lm5\forms\Quotes.scx"

The UI progress bar appears briefly and then disappears, but no SC2 files is generated, and no errors are shown.

**Comment by fdbozzo** [comment]
Thanks Matt, I'll take a look.

**Comment by mattslay** [comment]
In debug mode, I checked property  loCnv.c_TextErr, and I see these errors (see attached)

So, after I deleted the duplicate controls from the form in form designer, then it worked fine to generate the SC2 file.

![2018-11-02_17-59-50](https://user-images.githubusercontent.com/309016/47945006-08acbb80-decd-11e8-9cee-cf9c03970aa7.png)

I think you can close this issue now.

**Comment by fdbozzo** [comment]
Happy to know it Matt! :D

**Comment by fdbozzo** [comment]
Already fixed on v1.19.51.4
