### ISSUE TITLE
Issue with pj2 PRG2BIN in <TextFiles> section when path has parentheses - ")"

### ISSUE THREAD

**Issue by ngbrown** [fdbozzo/foxbin2prg#3]
I am getting this error on converting some of my pj2 files with PRG2BIN:

```
2016-07-10T13:51:44  ----------------------------------------------------------------------------------------------------
Error 36, Command contains unrecognized phrase/keyword.
analyzecodeblock_textfiles, 11436
lcFile			= LOWER( ALLTRIM( STRTRAN( CHRTRAN( NORMALIZE( STREXTRACT( tcLine, ".ITEM(", ")", 1, 1 ) ), ["], [] ), 'lcCurDir+', '', 1, 1, 1) ) )
FoxBin2Prg: [C:\VFP_SOURCE\FOXBIN2PRG\FOXBIN2PRG.EXE] (EXE Version: v1.19.47)
tc_InputFile = [C:\VFP_SOURCE\VFPAPPS\TEST.PJ2]
```

This also happens in the most recent preview.

I've traced it down to this minimal example:

```
	*<TextFiles>
	.ITEM(lcCurdir + '..\..\..\program files (x86)\microsoft visual foxpro 9\ffc\_frxcursor.h').Type = 'T'
	*</TextFiles>
```

Looking in `foxbin2prg.prg`, I see that the `STREXTRACT()` in `analyzecodeblock_textfiles` is the only one that doesn't have something more after the _cEndDelim_ `")"` parameter.  For example, `analyzeCodeBlock_ExcludedFiles` has `").Exclude"`.

So perhaps line 11436 should change `")"` to `").Type"` like so:

```
lcFile			= LOWER( ALLTRIM( STRTRAN( CHRTRAN( NORMALIZE( STREXTRACT( tcLine, ".ITEM(", ").Type", 1, 1 ) ), ["], [] ), 'lcCurDir+', '', 1, 1, 1) ) )
```

**Comment by fdbozzo** [comment]
Hi Nathan:

Thanks for the suggestion, I've fixed with it.
You can download **v1.19.48 Preview-5** from VFPx:
https://vfpx.codeplex.com/releases/view/116407

**Comment by ngbrown** [comment]
@fdbozzo thanks for your effort on this.  Your tool is making working with FoxPro better.
