### ISSUE TITLE
Project build setting to auto increment version always serialized as "0"

### ISSUE THREAD

**Issue by DanLauer** [fdbozzo/foxbin2prg#35]
To test, I changed the build setting to auto increment version number using both Project Manager and Project Explorer, then serialize the project. No matter what the state or which tool I use to set it, the serialization line reads:

```_AutoIncrement = "0"```

We code on branches and build on our main branch. We re-gen the binary project from the .pj2 when switching branches. With this issue, we have to manually enable the auto increment after every re-gen of the .pjx. This is fairly new, we think. The problem showed up for us sometime in the last several months, but we assumed it was our process until I got around to specifically testing today.

**Comment by DanLauer** [comment]
I realized I made a mistake in my testing. There is actually a difference in the way Project Manager sets this value vs the way Project Explorer sets it

Your code does this to serialize the auto increment setting:

```._AutoIncrement		= IIF( SUBSTR( tcDevInfo, 1788, 1 ) = CHR(1), '1', '0' )```

Project Manager sets the one byte ascii value of ```0```  for off or ```1``` for on, whereas Project Explorer sets ```0``` for off and ```255``` for on. With regard to build behavior, VFP appears to work either way.

I'm not sure whether this is a FoxBin2Prg issue or a Project Explorer issue.

**Comment by DougHennig** [comment]
Project Explorer does the equivalent of this:

loProject.AutoIncrement = llAutoIncrement

where loProject is a reference to the project object and llAutoIncrement is the desired value. If llAutoIncrement is .T., VFP stores CHR(255) to the value. So, it looks like a bug in VFP: turning on Auto Increment visually sets it to CHR(1) but doing it programmatically sets it to CHR(255).

I suggest FoxBin2PRG save the ASC value instead:

._AutoIncrement	= TRANSFORM(ASC(SUBSTR(tcDevInfo, 1788, 1)))

Doug

**Comment by fdbozzo** [comment]
Bug is fixed! Thank you for reporting and sorry to be late. Enjoy :)
PS: Thanks Doug! Your fix is into FoxBin2Prg :D
