### ISSUE TITLE
Incompatible with VFPA

### ISSUE THREAD

**Issue by eselje** [fdbozzo/foxbin2prg#36]
It must be doing some version checking that isn't expecting VFPA. A simple fix would be to invoke SYS(9018,0) to make VFPA return older version information. VFP9 and earlier would be unaffected.

```
Error 1098, Incorrect VFP 9 version - Missing SP1! Expected: 3504 or later, actual: 10.00.0000.1909
execute, 2902
FoxBin2Prg: [C:\DEV\FOX\THOR\THOR\THOR\TOOLS\COMPONENTS\FOXBIN2PRG\FOXBIN2PRG.EXE] (EXE Version: v1.19.51)
```

**Comment by GTGeek88** [comment]
Translation, in case you're lurking and wondering . . . Visual FoxPro Advanced. :-)

**Comment by rikaye** [comment]
Just ran into this myself. Any plans to add support for VFPA to FB2P, Fernando?

**Comment by fdbozzo** [comment]
Hello, guys: Since 1+ year now, I'm working on other technologies and I'm really not touching VFP, so I see a little complicated to keep maintaining this project and giving to it more hours :-| 
In some future I will try to address the remaining issues, but I'm really out of time occupied by many things I need to learn. Hope you understand :-)

**Comment by rikaye** [comment]
Thanks for following up, Fernando, and thanks for creating a fantastic tool. I'm using it everyday. I'll take a stroll through the code as this sounds like a fairly straightforward change. If it is, I'm happy to fork the project and submit the fix once I can resolve the issue.

**Comment by rikaye** [comment]
This appears to be the culprit. From the execute method:

`DO CASE
CASE VERSION(5) < 900 OR INT( VAL( SUBSTR( VERSION(4), RAT('.', VERSION(4)) + 1 ) ) ) < 3504`
`	ERROR loLang.C_INCORRECT_VFP9_VERSION__MISSING_SP1_LOC`

Easy enough to modify to handle VFPA. Taking the simplest approach I simply added another CASE at the beginning:

`CASE VERSION(5) = 1000`

Would you like me to submit this?

**Comment by fdbozzo** [comment]
Ok, Richard,

Thanks :)

**Comment by fdbozzo** [comment]
Bug is fixed! Thank you for reporting and sorry to be late. Enjoy :)
