### ISSUE TITLE
Error in latest build 1.19.57

### ISSUE THREAD

**Issue by msueping** [fdbozzo/foxbin2prg#53]
I receive the following error when using the updated version 1.19.57:

**Error 12, Variable 'LNFILECOUNT' is not found.
get_filesfromdirectory, 5208
DO c:\vfputils\thor\tools\components\foxbin2prg\foxbin2prg.exe WITH "SHOWMSG-PRG2BIN", "C:\Source\Repos\brokerWOLF\lwapp"

FoxBin2Prg: [C:\VFPUTILS\THOR\TOOLS\COMPONENTS\FOXBIN2PRG\FOXBIN2PRG.EXE] (EXE Version: v1.19.57)
lcInputFile_Type  = [D]
tc_InputFile = [C:\Source\Repos\brokerWOLF\lwapp]

 
Source file: C:\Source\Repos\brokerWOLF\lwapp**

As you can see, the parameter name is 'tnFileCount' but line 5208 is using '@lnFileCount'.

![bin2prg](https://user-images.githubusercontent.com/67658122/111347817-f4108e80-8655-11eb-8a95-5831cb8f38f3.png)

**Comment by kwesterlund** [comment]
Thanks for reporting this, I found the same issue.

**Comment by lscheffler** [comment]
Will be fixed in next release.
