### ISSUE TITLE
Ignoring extention in foxbin2prg.cfg

### ISSUE THREAD

**Issue by s-s-a** [fdbozzo/foxbin2prg#56]
1.19.61 ignores extentions in foxbin2prg.cfg
In all of my foxbin2prg.cfg:
extension: pj2=pjm
extension: vc2=vca
extension: sc2=sca
extension: fr2=fra
extension: lb2=lba
extension: mn2=mna
extension: db2=dba
extension: dc2=dca

After update to version 1.19.61 I got this:

****************************************************************************************************
FoxBin2Prg INIT  -  2021-03-30T09:57:11
****************************************************************************************************
FoxBin2Prg: [D:\WORK\TOOLS\FOXBIN2PRG\FOXBIN2PRG.EXE] (EXE Version: v1.19.61, FoxPro Version: 09.00.0000.7423)
- Internal CFG:  / External CFG: C:\PROGRA~2\MI61F2~1\CONFIG.FPW / CodePage Used: 1251)

> READING CFG VALUES FROM DISK:
	Using configuration file: D:\WORK\TOOLS\FOXBIN2PRG\FOXBIN2PRG.CFG
	FOXBIN2PRG.CFG > tcDebug:                    1

****************************************************************************************************
MAIN EXECUTION  2021-03-30T09:57:11
****************************************************************************************************
> EXTERNAL PARAMETERS:
	tc_InputFile:                 D:\Work\Italika\Forms\frm8.scx
	tcType:                       BIN2PRG
	tcTextName:                   0
	tlGenText:                    0
	tcDontShowErrors:             1
	tcDebug:                      1
	tcDontShowProgress:           1
	tlRelanzarError:              (empty)
	tcOriginalFileName:           (empty)  -> Will use Default []
	tcRecompile:                  D:\Work\Italika\Forms
	tcNoTimestamps:               1
	tcBackupLevels:               (empty)  -> Will use Default [1]
	tcClearUniqueID:              (empty)  -> Will use Default [.T.]
	tcOptimizeByFilestamp:        (empty)  -> Will use Default [0]

> CACHING CONFIG FOR DIRECTORY: D:\
	- Inheriting from: D:\WORK\TOOLS\FOXBIN2PRG\FOXBIN2PRG.CFG
> CACHING CONFIG FOR DIRECTORY: D:\WORK
	- Inheriting from: D:\WORK\TOOLS\FOXBIN2PRG\FOXBIN2PRG.CFG
> CACHING CONFIG FOR DIRECTORY: D:\WORK\ITALIKA
	- Inheriting from: D:\WORK\TOOLS\FOXBIN2PRG\FOXBIN2PRG.CFG

> READING CFG VALUES FROM DISK:
	Using configuration file: D:\WORK\ITALIKA\FOXBIN2PRG.CFG
	FOXBIN2PRG.CFG > ShowProgressbar:            1

> CACHING CONFIG FOR DIRECTORY: D:\WORK\ITALIKA\FORMS
	- Inheriting from: D:\WORK\ITALIKA\FOXBIN2PRG.CFG

> READING CFG VALUES FROM DISK:
	Using configuration file: D:\WORK\ITALIKA\FORMS\FOXBIN2PRG.CFG

> Using this settings:
	CFG_Actual:                 5 [SECONDARY]
	CFG_CachedAccess:           .F.
	tc_InputFile:               D:\Work\Italika\Forms\frm8.scx
	Foxbin2prg_ConfigFile:      D:\WORK\ITALIKA\FORMS\FOXBIN2PRG.CFG
	Language:                   EN ((auto))
	ShowProgressbar:            0
	ShowErrors:                 .F.
	ExtraBackupLevels:          1
	BackgroundImage:            D:\WORK\TOOLS\FOXBIN2PRG\foxbin2prg.jpg(Internal default)
	Debug:                      1
	HomeDir:                    1
	PJX_Conversion_Support      2
	VCX_Conversion_Support      2
	SCX_Conversion_Support      2
	FRX_Conversion_Support      2
	LBX_Conversion_Support      2
	MNX_Conversion_Support      2
	DBF_Conversion_Support      1
	DBC_Conversion_Support      2
	FKY_Conversion_Support      1
	MEM_Conversion_Support      1
	UseClassPerFile:            0
	ClassPerFileCheck:          .F.
	RedirectClassPerFileToMain: .F.
	RedirectClassType:          0
	OldFilesPerDBC:             .T.
	UseFilesPerDBC:             0
	RedirectFilePerDBCToMain:   .F.
	ItemPerDBCCheck:            .F.
	DBF_BinChar_Base64:         .T.
	DBF_IncludeDeleted:         .F.
	NoTimestamps:               .T.
	ClearUniqueID:              .T.
	OptimizeByFilestamp:        0
	RemoveNullCharsFromCode:    .T.
	RemoveZOrderSetFromProps:   .F.
	PRG_Compat_Level:           0
	Recompile:                  .T. (D:\Work\Italika\Forms)
	BodyDevInfo:                0
	ClearDBFLastUpdate:         .T.
	ExcludeDBFAutoincNextval:   0
	DBF_Conversion_Included     
	DBF_Conversion_Excluded     
	DBF_BinChar_Base64:         .T.
	DBF_IncludeDeleted:         .F.
	**extension: VC2              VC2
	extension: SC2              SC2
	extension: FR2              FR2
	extension: LB2              LB2
	extension: MN2              MN2
	extension: DB2              DB2
	extension: DC2              DC2
	extension: FK2              FK2
	extension: ME2              ME2**

> Option: BIN2PRG
> InputFile is a FILE

****************************************************************************************************
CONVERSION PROCESS  2021-03-30T09:57:11
****************************************************************************************************
> USING THIS SETTINGS: D:\WORK\ITALIKA\FORMS\FOXBIN2PRG.CFG  => D:\Work\Italika\Forms\frm8.scx
	c_OriginalFileName:           D:\Work\Italika\Forms\frm8.scx

	* Names capitalization program [D:\WORK\TOOLS\FOXBIN2PRG\filename_caps.exe] found
	c_foxbin2prg.changefileattribute >> [D:\Work\Italika\Forms\frm8.SC2] lnRet = 0, dwFileAttributes_Orig = -1

	Converting file D:\Work\Italika\Forms\frm8.**SC2**...
		- File: D:\Work\Italika\Forms\frm8.**SC2** (352.14/352.14 KiB)

FoxBin2Prg UNLOAD  -  2021-03-30T09:57:14
****************************************************************************************************

**Comment by lscheffler** [comment]
Ok. I will check it.   
Should I post if I have a solution on my fork or will you wait until Doug merges?
