### ISSUE TITLE
Tables without indexes cause an error that the "Table ____ is not marked as belonging to the _____ database

### ISSUE THREAD

**Issue by jstagerGH** [fdbozzo/foxbin2prg#58]
## ℹ Computer information

- VFP version: VFP9 SP2
- FoxBin2PRG version: 1.19.62

## 📝 Provide detailed reproduction steps (if any)

When converting a database table that **doesn't have any indexes** from a db2 to a dbf, the table no longer belongs to the proper database.

### ✔️ Expected result

The indexless table should remain attached to the proper database

### ❌ Actual result

When dbf is created it appears to be tagged to a "_fb2p.dbc" database and no longer part of our "lwdata.dbc". This causes an error when trying to open this table.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/82169086/114057967-0d75b680-9861-11eb-8652-27fb96816705.png)
![image](https://user-images.githubusercontent.com/82169086/114058097-2716fe00-9861-11eb-82fd-ce5801f67cdb.png)

**Comment by lscheffler** [comment]
The _fb2p.dbc is something temporary used I do not really understand. It should  not interfere with real DBC.   
What version of  foxbin2prg was used to create the db2?     
If created with an an version pre  1.19.60 , will this happen if you create the db2 with the recent version too?

**Comment by jstagerGH** [comment]
Hi @lscheffler we have tried with 1.19.51 to create db2 and it worked but using 1.19.62 it causes the error

**Comment by lscheffler** [comment]
FoxBin2Prg creates all tables to this fb2p.dbc and later changes the database with low level file access.   
This is called in writeBinaryFile_INDEXES - what is an odd place, and is now ignored by an condition dealing with existing or non existing indexes. There are other issues with this too.
I need to think through it.
