### ISSUE TITLE
Problem in latest update 1.19.64

### ISSUE THREAD

**Issue by Jimrnelson** [fdbozzo/foxbin2prg#64]
## ℹ Computer information

VFP version: VFP9SP2
FoxBin2PRG version: 1.19.64

## 📝 Provide detailed reproduction steps (if any)

I have not been able to verify that the updates for MN2 to MNX files work using today's update.

1 -- I took an existing menu
2 -- Made a minor modification to a caption and also to a call to a method from the menu item
3 -- Generate Menu
4 -- Committed and Pushed

Bill A pulled and run the menu.  My changes were not there.

However -- they were there in the MN2 file and other files.  We noted that the MPX had not changed (but have no idea whether this is relevant).

Furthermore, when Bill went in to modify the menu, he could see my changes; even after regenerated the menu and save it, his changes did not show up when he ran it.

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by lscheffler** [comment]
Hi @Jimrnelson    
I'm a bit puzzled with the push / pull problem. This project is about generating / regenerating VFP files. So if you follow
1. generate the mn2
2. move the menu binary files + mpr aside
3. regenerate the menu from mn2   
 
Does this produce the right mnx?    
1. generate the mpr from mpx
5. compare with original mpr    

do you see differences?

----
If you have problems using git I can provide help, but I recommend working through the first three chapters of [proGit](https://git-scm.com/book/en/v2) first and  [ohmygit](https://ohmygit.org/) second. Do not start with any git-GUI. Start on _bash_.

If you need to come out of the situation you are locked in, you can send me your email or just meet me in that what was once known as Universal Thread.

**Comment by lscheffler** [comment]
@Jimrnelson    
Additional to the above, do you have read [using with git](https://github.com/fdbozzo/foxbin2prg/blob/master/docs/FoxBin2Prg_git.md) on the docs?

**Comment by Jimrnelson** [comment]
You can close this issue.  The problems were elsewhere (including, but not limited to, user error).

Thanks
