### ISSUE TITLE
Incorrect version showing for v1.19.65

### ISSUE THREAD

**Issue by siara-cc** [fdbozzo/foxbin2prg#69]
## ℹ Computer information

- VFP version: 9
- FoxBin2PRG version: v1.19.65
- Last FoxBin2PRG version w/o bug (if available): v1.19.63

## 📝 Provide detailed reproduction steps (if any)

When running Txt -> Bin the progress bar is showing v1.19.64 even though v1.19.65 is installed.

Also this repo has releases till only v1.19.62 and unable to find later releases and notes.

### ✔️ Expected result

- Should show v1.19.65 on title bar when running FoxBin2Prg
- Is it possible to have releases and notes in Github?

### ❌ Actual result

- Showing v1.19.64 on title bar when running FoxBin2Prg v1.19.65
- Releases notes unavailable in Github for >v1.19.62

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/12986780/128361731-5bfe6399-c9ad-48a5-8eaf-4905518fc48b.png)

**Comment by DougHennig** [comment]
Sure, we could push the changes.

**Comment by lscheffler** [comment]
@siara-cc please do issues in _one problem one issue_ form. It's hard to address otherwise.

> Also this repo has releases till only v1.19.62 and unable to find later releases and notes.   
This is only the tags are missing. The code is recent. Since I provide the code and Doug is pushing, there are flaws from time to time. Sorry about this.

**Comment by lscheffler** [comment]
@siara-cc 

> Is it possible to have releases and notes in Github?

I do not grok this.  What do you expect?   
This repo is basically for deploying FoxBin2Prg via _Thor_, and to provide the source for participating. We do not create releases in the sense of deployment other then deploying via Thor. I do not know what github is doing under [Releases](https://github.com/fdbozzo/foxbin2prg/releases) - there are simply the tags listed. 

I was also a bit surprised to found the question under _Expected result_ section. I tend to ignore this if the problem is clear from the issue name. :)

**Comment by siara-cc** [comment]
Hi @lscheffler ,

Thank you for addressing the issue.  About the release notes, I thought it could be useful if the changes are mentioned in the description of Releases section, for people like me trying to figure out if we need to upgrade to a particular version.

The version displayed in the progress dialog is useful to show that I am using the correct version when discussing with other developers, particularly differences in files due to recent changes in format of DB2 files.  So I used the prescribed template to report the issue here.

I did not realise the problem faced because of reporting two issues in one. I will keep this in mind when reporting issues in future.

I would like to thank you for the time spent in looking into this and also for providing us a great tool !!

@DougHennig

**Comment by lscheffler** [comment]
@siara-cc    
You are perfectly fine with the problems. The version number and the change list issues are solved.    
The tag issue not (This is the links from the change-list will not work, for example) Normally the change-list shows the recent state of this repo. The changes are also visible via Thors update process.

I recommend  to use the latest version anyway, it's not a big deal to download via Thor or git. I try to address all changes, but sometimes minor hiccups will be changed quietly.
