### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by BoatrightTBC** [fdbozzo/foxbin2prg#7]
I started moving documentation from Codeplex into the wiki.  

Once I get those edited clean, it would make sense to incorporate them into the project in a "docs" or "documentation" folder, possibly as PDFs.

**Comment by fdbozzo** [comment]
Hi Rick:

The only think I don't like about PDFs in this case is that the require
separated maintenance, so at the end one need to update the web pages and
the PDF.

I will think about it.

Thanks for your efforts!

Fernando D. Bozzo

**Comment by DougHennig** [comment]
You can download the documentation from CodePlex by signing in and clicking the Download Wiki link on the home page. It downloads all of the VFPX documentation so it's over 100 MB but then you can just pick out the FoxBin2PRG files. They're already converted to Markdown format (MD files) which GitHub supports so no need to convert them to PDFs.

Doug

**Comment by BoatrightTBC** [comment]
AHA!   Didn't know that.  I'll do that, and edit the wiki pages to make them current then 
Nice.

**Comment by BoatrightTBC** [comment]
Doug, I see no such link on either the codplex homepage, or the vfpx homepage.  Help?

**Comment by fdbozzo** [comment]
I did see it. You must login with user/password first, then you can see
this "Download Wiki" option:


[image: Imágenes integradas 1]

2017-04-10 23:06 GMT+02:00 Rick Boatright <notifications@github.com>:
