### ISSUE TITLE
Converting MN2 to MNX ignores the programmer-defined "Pad Name" found in "Prompt Options" screen

### ISSUE THREAD

**Issue by Jimrnelson** [fdbozzo/foxbin2prg#74]
## ℹ Computer information

- VFP version: 9.00.0000.5815
- FoxBin2PRG version: 1.19.64
- Last FoxBin2PRG version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)

MN2 files show the Pad Names but they are ignored when re-creating the MNX files

It appears that this can be fixed in method analyzeCodeBlock_DefinePAD by adding the few lines of code (in red) below

![image](https://user-images.githubusercontent.com/81179335/148825318-fdffe593-3ef6-4239-9729-4eaf04ed9c70.png)

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/81179335/148825069-52c64c65-dac5-4a66-b447-a253f599a718.png)

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by lscheffler** [comment]
@Jimrnelson What do you think about forking, fixing and raising a merge request? Else, please post the code as code, at least I can copy-paste and do the painful part of the work.
:)

**Comment by lscheffler** [comment]
@Jimrnelson Have you tested the latest version for this problem?

**Comment by lscheffler** [comment]
Ic onsider this as closed.
