### ISSUE TITLE
Converting back a vcx from a vc2 a error is reported incorrect Class defined twice Error 1098.

### ISSUE THREAD

**Issue by bjornhoeksel** [fdbozzo/foxbin2prg#77]
## ℹ Computer information

- VFP version:  9 sp2
- FoxBin2PRG version: 1.19 (latest)
- Last FoxBin2PRG version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)

Converting back a vcx from a vc2 a error is reported incorrect Class defined twice.
This happens when name of control is same as name of control used on form

See sample attachment vc2 file if converted back to vcx problem is reported

Error 1098, 
Class defined twice.

problem is caused by the following code:
								SELECT TABLABIN
								LOCATE;
									FOR OBJNAME==loClase._ObjName
								IF FOUND() THEN
*SF 20211207
*SET STEP ON
									Error loLang.C_ClassTwice_Header_LOC + ;
										loLang.C_ClassTwice_Lib_LOC + JUSTFNAME( DBF() ) + ;
										loLang.C_ClassTwice_Class_LOC + loClase._ObjName+0h0D0A
								ENDIF &&FOUND() 

### ✔️ Expected result
No error 

[brl_obj.VC2.txt](https://github.com/fdbozzo/foxbin2prg/files/8122743/brl_obj.VC2.txt)

**Comment by lscheffler** [comment]
Just to be clear:   
So, you say the **name** of the control is the same name as the **class** of this very control.   
In your example:   
`	ADD OBJECT 'PGF_SETUP.Page1.cbo_brl_rule_type' AS cbo_brl_rule_type WITH ;
`

**Comment by lscheffler** [comment]
Inserting a class, the test just checks if the _Objname_ field of the vcx to create holds a string twice without checking for empty _Parent_, so it finds objects named equal to a class.

Since creating a merge is a lengthy process, and I like to incorporate #78, 
replace in the code pointed out by you
```
LOCATE;
FOR OBJNAME==loClase._ObjName
```
with
```
LOCATE;
FOR OBJNAME==loClase._ObjName AND EMPTY(Parent)
```
and rebuild the exe

**Comment by bjornhoeksel** [comment]
> Inserting a class, the test just checks if the _Objname_ field of the vcx to create holds a string twice without checking for empty _Parent_, so it finds objects named equal to a class.
> 
> Since creating a merge is a lengthy process, and I like to incorporate #78, replace in the code pointed out by you
> 
> ```
> LOCATE;
> FOR OBJNAME==loClase._ObjName
> ```
> 
> with
> 
> ```
> LOCATE;
> FOR OBJNAME==loClase._ObjName AND EMPTY(Parent)
> ```
> 
> and rebuild the exe

Hi 

I tested the suggested fix and it works ok
