### ISSUE TITLE
Last bar in menu files are in some situations not converted correctly back in the mnx file.

### ISSUE THREAD

**Issue by bjornhoeksel** [fdbozzo/foxbin2prg#79]
## ℹ Computer information

- VFP version:  9.0 sp2
- FoxBin2PRG version: [1.19.69](https://github.com/fdbozzo/foxbin2prg/releases/tag/v1.19.69)

## 📝 Provide detailed reproduction steps (if any)

Last bar in menu files are in some situations not converted correctly back in the mnx file.
See sample mn2 file. The bar close_pos  is not correct in converted mnx file objcode is not set.
I fix the problem by adding following line
```
loReg.OBJCODE	= C_OBJCODE_MENUOPTION_BARNUM	 in otherwise 

In code:
Do Case
Case Left ( m.lcBarName, 1 ) = '"'
	lcBarName   	= Substr( m.lcBarName, 2, Len( m.lcBarName ) - 2 )
	loReg.Name		= m.lcBarName
	loReg.OBJCODE	= C_OBJCODE_MENUOPTION_BARNUM
Case Isdigit( m.lcBarName )
*-- Bar#
	loReg.OBJCODE	= C_OBJCODE_MENUOPTION_BARNUM

Otherwise
*-- Es un BAR del sistema
	loReg.Name	= m.lcBarName
	
* this line to add by issue #79
	 loReg.OBJCODE	= C_OBJCODE_MENUOPTION_BARNUM	&& Bar#_
* /this line to add by issue #79

Endcase
```

 ### ✔️ Expected result

MNX with bar close_pos with objcode set correct

### ❌ Actual result

MNX with bar close_pos with objcode = 0

## 📷 Screenshots

[PID_MEN.zip](https://github.com/fdbozzo/foxbin2prg/files/8262424/PID_MEN.zip)

#### Edit 1 lscheffler:
Formatted code, added correct version number

#### Edit 2 lscheffler:
Commented code inserted

**Comment by lscheffler** [comment]
@bjornhoeksel Please give me a line number in the prg file where you added the code. If possible a snippet before and after, so that I see what is changed

**Comment by bjornhoeksel** [comment]
> @bjornhoeksel Please give me a line number in the prg file where you added the code. If possible a snippet before and after, so that I see what is changed

Hi I added the code around in my first message de code is at line nr = 28596. 
I added loReg.OBJCODE	= C_OBJCODE_MENUOPTION_BARNUM in the otherwise case.

**Comment by lscheffler** [comment]
@bjornhoeksel    
So we end up   
`loReg.OBJCODE = C_OBJCODE_MENUOPTION_BARNUM`   
in any case, and could move it out of the case?

**Comment by bjornhoeksel** [comment]
> @bjornhoeksel So we end up `loReg.OBJCODE = C_OBJCODE_MENUOPTION_BARNUM` in any case, and could move it out of the case?

Yes, you are right, it could move out the case loReg.OBJCODE = C_OBJCODE_MENUOPTION_BARNUM
For more cleaner code. You could place it just above the following lines above the case instead of in all case options

						loReg.ObjType		= C_OBJTYPE_MENUTYPE_OPTION
						lcBarName			= Alltrim( Strextract( tcLine, 'BAR ' , ' OF' ) )

Code beomes then something like
                                               loReg.OBJCODE = C_OBJCODE_MENUOPTION_BARNUM						
                                               loReg.ObjType		= C_OBJTYPE_MENUTYPE_OPTION
						lcBarName			= Alltrim( Strextract( tcLine, 'BAR ' , ' OF' ) )
