### ISSUE TITLE
Typo in German Translation "Ende desr Prozesses"

### ISSUE THREAD

**Issue by JoergSchneider** [fdbozzo/foxbin2prg#85]
## ℹ Computer information

- VFP version: 9.0.0.5815
- FoxBin2PRG version: 1.19.74
- Last FoxBin2PRG version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)

1. Convert bin to Text
2. End of Process shows Messagebox in German with Typo, see Screenshot.

### ✔️ Expected result
Ende des Prozesses.

### ❌ Actual result
Ende desr Prozesses

## 📷 Config

**Do not include your normal config.**
Please add your current full configuration.   
Create a config file via `DO FOXBIN2PRG.PRG WITH '-C','path-to-source\FoxBin.cfg'` , zip and add here.  

## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_
<img width="152" alt="image" src="https://user-images.githubusercontent.com/7488561/172610505-5b9928d1-225d-4e4f-a1c5-6149a1b9ad43.png">

**Comment by lscheffler** [comment]
So simple, I think I can fix it. Aside the docu ....
