### ISSUE TITLE
bin2Txt Operation on VCX loses leading spaces in Property Values

### ISSUE THREAD

**Issue by JoergSchneider** [fdbozzo/foxbin2prg#90]
## ℹ Computer information

- VFP version: 9
- FoxBin2PRG version: 1.19.76
- Last FoxBin2PRG version w/o bug (if available): -

## 📝 Provide detailed reproduction steps (if any)

1. Class in VCX with a Property e.g. cJoin
2. The Property contains a String with leading Spaces e.g.: cJoin = ' test'
3. Now I run Bin2Txt 
4. In the VC2 File the Property is listed without the leading space
5. Now I run txt2bin
6. In the VCX the Property is now: cJoin = 'test'

### ✔️ Expected result
VC2 - File
...
	*<DefinedPropArrayMethod>
		*p: cjoin		&& Test Property
		*p: _memberdata		&& XML Metadata for customizable properties
	*</DefinedPropArrayMethod>

	cjoin =  Test		&& Test Property

### ❌ Actual result
	*<DefinedPropArrayMethod>
		*p: cjoin		&& Test Property
		*p: _memberdata		&& XML Metadata for customizable properties
	*</DefinedPropArrayMethod>

	cjoin = Test		&& Test Property

## 📷 Config

**Do not include your normal config.**
Please add your current full configuration.   
Create a config file via `DO FOXBIN2PRG.PRG WITH '-C','path-to-source\FoxBin.cfg'` , zip and add here.  

## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by lscheffler** [comment]
Both operations 2Text and 2Bin do an `Alltrim()` operation. It will require a complete different storage structure to keep the spaces.

Until that it might be useful to store such data in the expression form `=" Value "` to the property.

See #91, #92
